### ISSUE TITLE
npm install 直接报错了

### ISSUE THREAD

**Issue by q9887777** [alex8088/electron-micro-app#1]
deprecated electron-osx-sign@0.5.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
npm ERR! code 1
npm ERR! path D:\jmgx1\electron-app\elec2\node_modules\electron
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\game\AppData\Local\Temp\postinstall-0486d303.cmd
npm ERR! RequestError: connect ETIMEDOUT 20.205.243.166:443
npm ERR!     at ClientRequest.<anonymous> (D:\jmgx1\electron-app\elec2\node_modules\got\source\request-as-event-emitter.js:178:14)
npm ERR!     at Object.onceWrapper (node:events:628:26)
npm ERR!     at ClientRequest.emit (node:events:525:35)
npm ERR!     at ClientRequest.origin.emit (D:\jmgx1\electron-app\elec2\node_modules\@szmarczak\http-timer\source\index.js:37:11)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:494:9)
npm ERR!     at TLSSocket.emit (node:events:513:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\game\AppData\Local\npm-cache\_logs\2022-10-20T09_22_52_750Z-debug-0.log

**Comment by alex8088** [comment]
网络问题，多试一下

**Comment by alex8088** [comment]
@q9887777 问题是否解决
